### ISSUE TITLE
Desktop integration of app icon

### ISSUE THREAD

**Issue by debloper** [debloper/exorcist#5]
As of now with `AppImage` & `electron-builder` there's seems to be no reasonable way to make app icons work consistently across Linux DE. We are left with two choices:
1. Ignore the icons not showing, focus on the app's core features & performances
2. Use other distribution formats (traditional `deb`, `rpm`, `pacman` or newer `snap`, `flatpak` etc.)

At the moment, I'm personally against the idea of `#2` because:
- **non-inclusivity:** distro specific packages (`deb`, `rpm`, `pacman` etc.) aren't an exhaustive list
- **addon deps:** newer packages *require* installing their package integration/manager tools (for AppImage that's optional)
- **fragmentation:** setting up and maintaining multitple formats (for inclusivity) also leads to gradual fragmentation (as well as overheads, and possible feature imparity)

We can also debate the possibility of using a different packaging utility, but there isn't any good `electron-builder` alternative or a good way to

- extract AppImage files
- add necessary scripts to cache icons
- repackage it back again

So, for now, we're stuck with these two tools, unless until something changes.

---

So, we're going ahead with **Plan A**:
```
Ignore the icons not showing, focus on the app's core features & performances.
```

---

A consolidated analysis to understand the issue with `#1` (thanks @probonopd):
https://github.com/AppImage/appimaged/issues/30

**Comment by probonopd** [comment]
> there's seems to be no reasonable way to make app icons work consistently across Linux DE

Can you describe in more detail what exactly is not working?

If the application sets the icon on the window, and if the desktop file uses the StartupWMClass field in the .desktop file correctly, then it should work sufficiently?

**Comment by debloper** [comment]
> Can you describe in more detail what exactly is not working?

In our case, we're avoiding the use of @TheAssassin/AppImageLauncher (as mentioned).

With that in hand, the issues are:
1. If SVG icon is used, `.desktop` file spec leaves it to DE devs' imagination how/whether they should work. Nothing to do with AppImage.
2. If the app was opened by clicking, the hicolor PNG icons (even if all necessary resolutions exist) won't show up (the workarounds of caching the icons before launching the app is simply a overhead no one should have to go through)
3. If the app was launched with CLI, there's a way to make it show the icon - but people who open apps with shell don't care about icons, and people who care about icons don't open apps with shell (in general).

Only thing I can request _you_ to take care of is reducing the disconnect between 2 & 3. And of course, thanks for the awesome tool. Even with some limitations, it's still my favorite package distribution mechanism on *nix.

**Comment by probonopd** [comment]
Thanks @debloper. I agree that the current state is not ideal, but I am not sure what we could do from the AppImage side to improve things without the XDG specifications and/or desktop environments being changed. Please let me know if you have concrete ideas how to tackle the issues you've described. Thanks for using AppImage.

**Comment by martinszeltins** [comment]
I created a simple Nautilus extension for ".app" bundle support kind of like what MacOS does

https://github.com/martinszeltins/nautilus-app-bundle-extension
